# Generated by Django 4.0.4 on 2022-09-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='d_description',
            field=models.TextField(default=None, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discipline',
            name='d_price',
            field=models.IntegerField(default=1, verbose_name='Цена обучения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discipline',
            name='d_name',
            field=models.CharField(max_length=20, verbose_name='Название'),
        ),
    ]
