# Generated by Django 4.0.4 on 2022-09-22 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_discipline_d_description_discipline_d_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='d_description',
            field=models.TextField(default='None', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='d_price',
            field=models.IntegerField(default=9, verbose_name='Цена обучения'),
        ),
    ]
