# Generated by Django 4.0.4 on 2022-09-22 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_discipline_d_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='d_description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='d_price',
            field=models.IntegerField(null=True, verbose_name='Цена обучения'),
        ),
    ]
