# Generated by Django 3.1.8 on 2022-10-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20221013_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_name', models.CharField(max_length=20, verbose_name='Имя')),
                ('email', models.EmailField(max_length=30)),
            ],
        ),
    ]
