# Generated by Django 3.1.8 on 2022-10-16 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_visible',
        ),
        migrations.AddField(
            model_name='question',
            name='q_email',
            field=models.EmailField(default='q123@mail.ru', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='q_name',
            field=models.CharField(default='name', max_length=20, verbose_name='Имя'),
            preserve_default=False,
        ),
    ]
